### ISSUE TITLE
"Step" text is off screen

### ISSUE THREAD

**Issue by NateBrune** [SirCmpwn/self-hosted#1]
![alt text](http://i.gyazo.com/dd9018bc73137a45a9263275571a1445.png "")
![alt text](http://i.gyazo.com/2e773465b7e93a7356902109c77a1a22.png "")
Unless I go f11 full screen, the steps arent displayed properly and go off the page.
I am running firefox with bspwm on arch linux fyi.

I dont think bspwm is screwing things up though.

**Comment by SirCmpwn** [comment]
See the readme for more details.

**Comment by NateBrune** [comment]
lol okay sorry :/ I was just trying to show it to you if you didn't know
